import type { TadaDocumentNode } from '#/graphql'
import { print } from 'graphql'

export interface IFetcher {
  /**
   * Fetches data from the Start.gg GraphQL API.
   *
   * @template Result The expected type of the data returned in the `data` field of the response.
   * @template Variables The type of the variables accepted by the GraphQL query.
   * @param {TadaDocumentNode<TResult, TVariables>} document The GraphQL document (query or mutation) generated by `tada`.
   * @param {Variables} variables The variables to be sent with the GraphQL query.
   * @param {RequestInit} [init] Optional `RequestInit` object to customize the fetch request.
   * @returns A promise that resolves to an object containing the `data` from the GraphQL response.
   */
  fetch: <TResult, TVariables>(
    document: TadaDocumentNode<TResult, TVariables>,
    variables: TVariables,
    init?: RequestInit,
  ) => Promise<{
    data: TResult
  }>
}

export class Fetcher implements IFetcher {
  async fetch<TResult, TVariables>(
    document: TadaDocumentNode<TResult, TVariables>,
    variables: TVariables,
    init?: RequestInit,
  ) {
    const query = print(document)
    const url = `https://www.start.gg/api/-/gql?query=${encodeURIComponent(query)}&variables=${encodeURIComponent(
      JSON.stringify(variables),
    )}`
    const response = await fetch(url, {
      method: 'GET',
      credentials: 'omit',
      mode: 'cors',
      ...init,
    })

    if (!response.ok) {
      const errorText = await response.text()
      throw new Error(`Start.gg API Error: ${response.status} - ${errorText}`)
    }

    const result = await response.json()

    return result as {
      data: TResult
    }
  }
}
